### ISSUE TITLE
Implement `Serialize/Deserialize` for the core structs?

### ISSUE THREAD

**Issue by kinghajj** [elliottneilclark/rs-poker#21]
I'm working on a [WebAssembly-based Texas Hold'em](https://github.com/kinghajj/netholdem) game. It will use WebSockets to send bincode-encoded messages between the client and server. To make things simple I'd prefer including `Card` structs directly in these messages, and not have to make a series of wrapper structs. But, unfortunately, the structs in this crate don't implement the serialization traits. Is there any interest in this? It would require adding `serde` as a dependency, but that's pretty ubiquitous anyway.

**Comment by elliottneilclark** [comment]
Yes, let me see how we can do that as an optional feature that can be turned on and off.
