### ISSUE TITLE
Bug when parsing a range containing only a pair

### ISSUE THREAD

**Issue by clemux** [elliottneilclark/rs-poker#70]
While playing with `RangeParser::parse_one`, I stumbled upon this bug:

```rust
    #[test]
    fn test_single_pair() {
        let c = RangeParser::parse_one("22").unwrap();
        assert_eq!(6, c.len());
    }
```

That fails because the range contains `Hand([Card(2s), Card(2s)]`.

Since there is no modifier, `gap` equals `None` [here](https://github.com/elliottneilclark/rs-poker/blob/ba3aa9f5edf2c8c6d7f6be6d9db717e44414b1f9/src/holdem/parse.rs#L471) and `RangeIter::stat` is used instead of `RangeIter::pair`.

**Comment by elliottneilclark** [comment]
Merged, thank you!
